// "use client";
import { Inter } from 'next/font/google'
import './globals.css'
// import { motion,AnimatePresence } from "framer-motion";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <AnimatePresence>
          <motion.div 
          whileHover={{ scale: 1.2 }}
          whileTap={{ scale: 1.1 }}
          drag="x"
          dragConstraints={{ left: -100, right: 100 }}> */}
        {children}
        {/* </motion.div>
        </AnimatePresence> */}
        </body>
    </html>
  )
}
